project_id = "fjaneryjjgesujinlbix"

[functions.parse-resume]
verify_jwt = true

[functions.vapi-interview]
verify_jwt = true

[functions.evaluate-interview]
verify_jwt = true

[functions.did-stream]
verify_jwt = true

[functions.generate-aptitude-questions]
verify_jwt = true

[functions.simli-config]
verify_jwt = false
